name: terraform Actions Demo
on: 
  push:
    branches:
      - main

jobs: 
  run-terraform:
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: create infra  
      - run: |
          cd aws-infra
          terraform init
          terraform plan
          terraform --auto-approve
